CREATE DATABASE CompanyDB;

USE CompanyDB;

CREATE TABLE Departments (
	DNum INT PRIMARY KEY IDENTITY(1,1),
	DName NVARCHAR(100) NOT NULL UNIQUE,
	HiringDate DATE DEFAULT GETDATE() CHECK (HiringDate >= '2025-06-01'),
	MgrSSN INT -- FK (ALTER)
);

CREATE TABLE Employees (
	SSN INT PRIMARY KEY,
	FName NVARCHAR(50) NOT NULL,
	LName NVARCHAR(50) NOT NULL,
	BirthDate DATE,
	Gender CHAR(1) CHECK (Gender IN ('M', 'F')),
	DNum INT NOT NULL DEFAULT 1,-- FK
	SupSSN INT, -- FK
	FOREIGN KEY (DNum) REFERENCES Departments(DNum)
	ON DELETE SET DEFAULT ON UPDATE CASCADE,
	FOREIGN KEY (SupSSN) REFERENCES Employees(SSN)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);

ALTER TABLE Departments
ADD CONSTRAINT FK_MgrSSN FOREIGN KEY (MgrSSN) REFERENCES Employees(SSN);


CREATE TABLE DeptLocations (
	DNum INT REFERENCES Departments(DNum)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	DLocation NVARCHAR(100),
	PRIMARY KEY (DNum, DLocation)
);

CREATE TABLE Projects (
	PNum INT PRIMARY KEY IDENTITY(1,1),
	PName NVARCHAR(100) NOT NULL,
	LocationCity NVARCHAR(100) DEFAULT 'Cairo',
	DNum INT NULL REFERENCES Departments(DNum)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

CREATE TABLE WorkOnProject (
	SSN INT REFERENCES Employees(SSN) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	PNum INT REFERENCES Projects(PNum)
	ON DELETE NO ACTION ON UPDATE NO ACTION,

	WorkingHours DECIMAL(5,2) NOT NULL DEFAULT 000.00,

	PRIMARY KEY (SSN, PNum)
);

CREATE TABLE Dependents (
	SSN INT REFERENCES Employees(SSN) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	DName NVARCHAR(100) NOT NULL,
	BirthDate DATE,
	Gender CHAR(1) CHECK (Gender = 'F' OR Gender = 'M'),

	PRIMARY KEY (SSN, DName)
);


-- Alter Operations

ALTER TABLE Employees
ADD Email NVARCHAR(150) NOT NULL;

ALTER TABLE Employees
ALTER COLUMN Email NVARCHAR(100);

ALTER TABLE Employees
ADD CONSTRAINT EMAIL_UNIQUE  UNIQUE (Email);

ALTER TABLE Employees
DROP CONSTRAINT EMAIL_UNIQUE;

